// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  benefits: dynamic(() => import("./Benefits")),
  blog: dynamic(() => import("./Blog")),
  cta_section: dynamic(() => import("./CtaSection")),
  faqs: dynamic(() => import("./Faqs")),
  hero: dynamic(() => import("./Hero")),
  logo_slider: dynamic(() => import("./LogoSlider")),
  menu_items: dynamic(() => import("./MenuItems")),
  rich_text: dynamic(() => import("./RichText")),
  service: dynamic(() => import("./Service")),
};
